---
title: "Gdelt Project - Thompson"
author: "Josh Thompson"
date: "2024-04-24"
output: 
  html_document:
    toc: True
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plotly)
```

## Top-10 By Mention W/ Titles

```{r}
top10_byMention_wTitles <- readRDS('topTenByMention_WithTitles.rds')
knitr::kable(top10_byMention_wTitles)
```

## Choropleth Map of Weighted Average Tone

```{r}
tone_map <- readRDS('tone_map.rds')

wavetone_map <- ggplot(tone_map, aes(x = long, y = lat, group = group, fill = weighted_avg_tone, hovertext = paste(region, '\nWeighted Average Tone:', round(weighted_avg_tone, 3)))) +
  borders("world", colour = "black", fill = 'gray') +
  geom_polygon(colour = "black") +
  scale_fill_gradient2(low="red", mid = "yellow", high="darkgreen", limits = c(-10,10)) +
  labs(title = paste('Weighted Average Tone per Country', '\nAll news stories on', '2024-04-24\n' ))
ggplotly(wavetone_map, tooltip = 'text') %>% style(hoverlabel = list(bgcolor = "white"))
```
