---
title: "GDELT Tone Mapping"
author: "Tim Gabriel"
date: "2024-04-15"
output: html_document
---

```{r, echo=FALSE}
library(GDELTtools)
library(dplyr)
library(urltools)
library(readxl)
library(tidyr)
```

# Access dataset for one day

```{r}
apr16 <- GetGDELT("2024-04-16")
apr16
```
# Gather all mentions of an event, Pull URL domains with respective tones

```{r}
apr16 %>%
  group_by(EventCode,Actor1Geo_Lat,Actor1Geo_Long,ActionGeo_Lat,ActionGeo_Long) %>%
  summarize(count=n(), tone = list(AvgTone), URLs = list(SOURCEURL), .groups="drop") %>%
  arrange(desc(count)) %>%
  select(URLs,tone) %>%
  slice(1) %>%
  unnest(c(URLs,tone)) %>%
  mutate(domain = (domain(URLs))) %>%
  select(URLs, domain, tone) -> topStory
topStory
```


# Sort these mentions by their country of origin.

```{r}
countryDomains <- read_excel("countryDomains.xlsx")
topStory %>% 
  mutate(suffix = sub(".+\\.", ".", domain)) %>%
  left_join(countryDomains, by = c("suffix"="domain")) -> df2
df2
```

# Removing NAs removes majority of rows

```{r}
df2 %>% na.omit() -> URLlist
URLlist
```

# Calculate Average Tone by Country

```{r}
URLlist %>%
  group_by(country) %>%
  summarize(meanTone=mean(tone) , .groups="drop") %>%
  arrange(meanTone) -> df3
df3
```

# Map Average Tone by Country, edited entries for Iran, China, US

```{r fig.width=10}
library(sf)
library(ggplot2)
worldShapeFiles <- read_sf("TM_WORLD_BORDERS_SIMPL-0.3.shp")
df3 %>%
  mutate(country = replace(country, 1, "Iran (Islamic Republic of)")) %>%
  mutate(country = replace(country, 2, "China")) %>%
  mutate(country = replace(country, 4, "United States")) ->df4

worldShapeFiles %>%
  left_join(df4, by = c("NAME"="country")) -> df5

ggplot(df5) +
  geom_sf(aes(fill=meanTone)) +
  scale_fill_distiller(palette="Reds",direction=1, name="",na.value="gray") +
  labs(title="Average Tone by Country")+
  theme_void()
```
